import DimensionCommand from './DimensionCommand';
// ...existing code...
const commands = {
  // ...existing commands...
  dimension: new DimensionCommand(),
};
// ...existing code...
export default commands;
